/api/v1/typeDocument/create:
  post:
    tags:
      - Crear Tipo de documento
    description: Crear un tipo de documento en el sistema.
    security:
    - bearerAuth: []
    produces:
      - application/json
    requestBody:
      content:
        application/json:
          schema:
              $ref: '#/definitions/Role'
    responses:
      200:
        description: Petición exitosa
        content:
          application/json:
            schema:
              type: object
              properties:
                response:
                  type: object
                  properties:
                    status:
                      type: bool
                    message:
                      type: string
                msj:
                  type: string
                  description: Mensaje de respuesta 
            example:
              {
                  "state": true,
                  "message": "Rol creado correctamente"
              }