/api/v1/role/getRoles:
  get:
    tags:
      - Listar roles
    security:
    - bearerAuth: []
    description: listar roles.
    produces:
      - application/json
    responses:
      200:
        description: Petición exitosa
        content:
          application/json:
            schema:
              type: array         
            example:
              {
                "state": true,
                "roles": [
                  {
                    "id": 1,
                    "name": "administrador"
                  },
                  {
                    "id": 2,
                    "name": "estudiante"
                  },
                  {
                    "id": 3,
                    "name": "test"
                  }
                ]
              }
